### ISSUE TITLE
批量扫描有点慢，希望可以显示个进度条

### ISSUE THREAD

**Issue by ThestaRY7** [lcvvvv/kscan#1]
类似于Oneforall的那种吧
我扫的文件有1600个域名。。

**Comment by ThestaRY7** [comment]
![image](https://user-images.githubusercontent.com/48352738/108593151-024bf180-73ad-11eb-8b83-6a56019d9163.png)

**Comment by lcvvvv** [comment]
这个问题近期会解决，现在的逻辑是所有地址一次性压入队列再开始扫描，所以初始化会比较慢。后续会改成边压入边扫描

**Comment by lcvvvv** [comment]
问题已解决
