### ISSUE TITLE
ssh弱口令root/123456，要指定账号密码才可以成功,看默认字典有root/123456

### ISSUE THREAD

**Issue by GGyao** [lcvvvv/kscan#103]
![image](https://user-images.githubusercontent.com/38530938/195329492-805e306d-c202-4011-af63-5ae993ca14eb.png)

**Comment by lcvvvv** [comment]
![图片](https://user-images.githubusercontent.com/49975427/195608292-7b3d1d5a-c392-4886-baa9-f6a22b974d7f.png)
本地测试 没问题，是不是存在其他因素？？
用其他工具能爆破出来吗？
