### ISSUE TITLE
MacOS Ventura 

### ISSUE THREAD

**Issue by Teicu** [lcvvvv/kscan#107]
Hi, 

the latest version of mac doesn't work, I tried both versions and it doesn't work 

**zsh: bad CPU type in executable:** 

**zsh: segmentation fault** 

Cheers

**Comment by lcvvvv** [comment]
m1?

**Comment by Teicu** [comment]
MacOS Ventura 2019
2,6 GHz 6-Core Intel Core i7

**Comment by lcvvvv** [comment]
https://github.com/lcvvvv/kscan/releases/download/v1.85/kscan_darwin_amd64.zip

**Comment by Teicu** [comment]
Hi, I get exactly the same errors. Anyway I compiled it manually in the end.

Cheers
