### ISSUE TITLE
域名识别不了吗

### ISSUE THREAD

**Issue by yz1639** [lcvvvv/kscan#109]
![image](https://user-images.githubusercontent.com/44149984/199147463-0656a038-a258-4fef-94db-ef701f577ada.png)
为什么识别不了   是不能使用域名吗  带上协议头 `http` `https` 也用不了

**Comment by lcvvvv** [comment]
奇怪，mac没这个问题，我修改下

**Comment by lcvvvv** [comment]
ok了，再试试
