### ISSUE TITLE
扫描报错了

### ISSUE THREAD

**Issue by teamtopkarl** [lcvvvv/kscan#11]
64位版本报错
![image](https://user-images.githubusercontent.com/18065690/117134489-3d6c9700-add8-11eb-9f96-0771fa31fc4e.png)

**Comment by teamtopkarl** [comment]
panic: syscall: string with NUL passed to StringToUTF16

goroutine 37688 [running]:
syscall.StringToUTF16(...)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/syscall/syscall_windows.go:31
syscall.StringToUTF16Ptr(0xc00bc0684e, 0x5, 0x5ac)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/syscall/syscall_windows.go:85 +0x85
net.(*Resolver).lookupPort(0xc91620, 0xa47060, 0xc00b993020, 0xc00b5fd8d0, 0x3, 0xc00bc0684e, 0x5, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/net/lookup_windows.go:192 +0xf1
net.(*Resolver).LookupPort(0xc91620, 0xa47060, 0xc00b993020, 0xc00b5fd8d0, 0x3, 0xc00bc0684e, 0x5, 0x0, 0x203002e, 0x1)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/net/lookup.go:346 +0xb9
net.(*Resolver).internetAddrList(0xc91620, 0xa47060, 0xc00b993020, 0xc00b5fd8d0, 0x3, 0xc00bc06840, 0x13, 0x0, 0x0, 0x0, ...)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/net/ipsock.go:252 +0x978
net.(*Resolver).resolveAddrList(0xc91620, 0xa47060, 0xc00b993020, 0x767e65, 0x4, 0xc00b5fd8d0, 0x3, 0xc00bc06840, 0x13, 0x0, ...)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/net/dial.go:222 +0x4a5
net.(*Dialer).DialContext(0xc008169c80, 0xa47020, 0xc00000a038, 0xc00b5fd8d0, 0x3, 0xc00bc06840, 0x13, 0x0, 0x0, 0x0, ...)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/net/dial.go:404 +0x231
net.(*Dialer).Dial(...)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/net/dial.go:349
net.DialTimeout(0xc00b5fd8d0, 0x3, 0xc00bc06840, 0x13, 0x165a0bc00, 0xc008169d50, 0x40c2e3, 0x2, 0x203002d)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/net/dial.go:335 +0xbc
github.com/lcvvvv/gonmap/simplenet.Send(0xc000a88c13, 0x3, 0xc00bc06840, 0x13, 0xc0003cf908, 0x4, 0x165a0bc00, 0x200, 0x30, 0x739480, ...)
        /Users/kv2/Project/go/pkg/mod/github.com/lcvvvv/gonmap@v0.1.17/simplenet/simplenet.go:14 +0x93
github.com/lcvvvv/gonmap.(*probe).scan(0xc000126930, 0xc00006a720, 0xb5a3a712c412f900, 0xc0032d8000, 0xb50000c007ad43c0, 0x13, 0xc008169e78)
        /Users/kv2/Project/go/pkg/mod/github.com/lcvvvv/gonmap@v0.1.17/type-probe.go:59 +0x128
github.com/lcvvvv/gonmap.(*Nmap).getPortInfo(0xc003c65420, 0xc000126930, 0xc00006a720, 0x0, 0xc00310c8a8)
        /Users/kv2/Project/go/pkg/mod/github.com/lcvvvv/gonmap@v0.1.17/gonmap.go:147 +0xde
github.com/lcvvvv/gonmap.(*Nmap).Scan(0xc003c65420, 0xc00d2a2b80, 0xe, 0x2329, 0xa42e20)
        /Users/kv2/Project/go/pkg/mod/github.com/lcvvvv/gonmap@v0.1.17/gonmap.go:120 +0x330
github.com/lcvvvv/gonmap.(*Nmap).safeScanSub(0xc003c65420, 0xc00d2a2b80, 0xe, 0x2329, 0xa47060, 0xc00b992fc0, 0xc00b9e2960)
        /Users/kv2/Project/go/pkg/mod/github.com/lcvvvv/gonmap@v0.1.17/gonmap.go:101 +0x50
created by github.com/lcvvvv/gonmap.(*Nmap).SafeScan
        /Users/kv2/Project/go/pkg/mod/github.com/lcvvvv/gonmap@v0.1.17/gonmap.go:89 +0x12d
panic: syscall: string with NUL passed to StringToUTF16

goroutine 37759 [running]:
syscall.StringToUTF16(...)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/syscall/syscall_windows.go:31
syscall.StringToUTF16Ptr(0xc00bc0684e, 0x5, 0x5c4)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/syscall/syscall_windows.go:85 +0x85
net.(*Resolver).lookupPort(0xc91620, 0xa47060, 0xc00b964540, 0xc00bc034f8, 0x3, 0xc00bc0684e, 0x5, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/net/lookup_windows.go:192 +0xf1
net.(*Resolver).LookupPort(0xc91620, 0xa47060, 0xc00b964540, 0xc00bc034f8, 0x3, 0xc00bc0684e, 0x5, 0x0, 0x203002e, 0x1)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/net/lookup.go:346 +0xb9
net.(*Resolver).internetAddrList(0xc91620, 0xa47060, 0xc00b964540, 0xc00bc034f8, 0x3, 0xc00bc06840, 0x13, 0x0, 0x0, 0x0, ...)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/net/ipsock.go:252 +0x978
net.(*Resolver).resolveAddrList(0xc91620, 0xa47060, 0xc00b964540, 0x767e65, 0x4, 0xc00bc034f8, 0x3, 0xc00bc06840, 0x13, 0x0, ...)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/net/dial.go:222 +0x4a5
net.(*Dialer).DialContext(0xc00de23c80, 0xa47020, 0xc00000a038, 0xc00bc034f8, 0x3, 0xc00bc06840, 0x13, 0x0, 0x0, 0x0, ...)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/net/dial.go:404 +0x231
net.(*Dialer).Dial(...)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/net/dial.go:349
net.DialTimeout(0xc00bc034f8, 0x3, 0xc00bc06840, 0x13, 0x165a0bc00, 0x17f, 0x0, 0x9, 0x203002f)
        /usr/local/Cellar/go/1.14.2_1/libexec/src/net/dial.go:335 +0xbc
github.com/lcvvvv/gonmap/simplenet.Send(0xc000a88c13, 0x3, 0xc00bc06840, 0x13, 0xc0003cf908, 0x4, 0x165a0bc00, 0x200, 0x30, 0x739480, ...)
        /Users/kv2/Project/go/pkg/mod/github.com/lcvvvv/gonmap@v0.1.17/simplenet/simplenet.go:14 +0x93
github.com/lcvvvv/gonmap.(*probe).scan(0xc000126930, 0xc00006a720, 0xb5a3a712c412f900, 0xc003e160d0, 0xb50000c003270000, 0x12, 0xc00de23e78)
        /Users/kv2/Project/go/pkg/mod/github.com/lcvvvv/gonmap@v0.1.17/type-probe.go:59 +0x128
github.com/lcvvvv/gonmap.(*Nmap).getPortInfo(0xc007097180, 0xc000126930, 0xc00006a720, 0x0, 0xc00310c8a8)
        /Users/kv2/Project/go/pkg/mod/github.com/lcvvvv/gonmap@v0.1.17/gonmap.go:147 +0xde
github.com/lcvvvv/gonmap.(*Nmap).Scan(0xc007097180, 0xc00d2a2b60, 0xd, 0x2329, 0xc00dc0b5c0)
        /Users/kv2/Project/go/pkg/mod/github.com/lcvvvv/gonmap@v0.1.17/gonmap.go:120 +0x330
github.com/lcvvvv/gonmap.(*Nmap).safeScanSub(0xc007097180, 0xc00d2a2b60, 0xd, 0x2329, 0xa47060, 0xc00b9644e0, 0xc00b90de60)
        /Users/kv2/Project/go/pkg/mod/github.com/lcvvvv/gonmap@v0.1.17/gonmap.go:101 +0x50
created by github.com/lcvvvv/gonmap.(*Nmap).SafeScan
        /Users/kv2/Project/go/pkg/mod/github.com/lcvvvv/gonmap@v0.1.17/gonmap.go:89 +0x12d

**Comment by lcvvvv** [comment]
是已启动就报错，还是扫描到一半才报错？

**Comment by teamtopkarl** [comment]
32位也有这问题，是扫到一半出现

**Comment by teamtopkarl** [comment]
扫到一半的时候，32位也是同样的问题------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年5月7日(星期五) 上午10:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lcvvvv/kscan] 扫描报错了 (#11)

**Comment by lcvvvv** [comment]
试一下最新版，应该已经解决了

**Comment by lcvvvv** [comment]
现在会对协程进行异常捕获，不会再出现单个协程崩溃而导致整个程序崩溃的情况了。
