### ISSUE TITLE
端口无法扫描到

### ISSUE THREAD

**Issue by 363401794** [lcvvvv/kscan#110]
最新版1.8.5扫不到80端口。

**Comment by 363401794** [comment]
实测1.7.6扫80出的来，最新版不行





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月2日(星期三) 下午5:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [lcvvvv/kscan] 端口无法扫描到 (Issue #110)





 
有问题的资产，单独扫80试试

**Comment by 363401794** [comment]
1.80以上都不行了

**Comment by 363401794** [comment]
1.80以上都不行

**Comment by lcvvvv** [comment]
加我微信详聊下

**Comment by 363401794** [comment]
您微信是？





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月3日(星期四) 上午9:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [lcvvvv/kscan] 端口无法扫描到 (Issue #110)





 
加我微信详聊下

**Comment by 363401794** [comment]
我微信  tzh363401794
