### ISSUE TITLE
出现新的报错

### ISSUE THREAD

**Issue by teamtopkarl** [lcvvvv/kscan#12]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x30 pc=0x6c679b]

goroutine 432 [running]:
kscan/run.(*HttpFinger).LoadHttpsResponse(...)
        /Users/kv2/Project/Gkscan/run/type-urlfinger.go:169
kscan/run.getUrlBanner(0xc00d468a80, 0x2e)
        /Users/kv2/Project/Gkscan/run/scan.go:73 +0x1eb
kscan/run.GetPortBanner(0xc00c459820, 0x13, 0xc006fe5030, 0xc00d4ec270)
        /Users/kv2/Project/Gkscan/run/scan.go:50 +0x59f
kscan/run.scanMainSub(0xcb3d60, 0xce2bd0, 0xc006fe5030)
        /Users/kv2/Project/Gkscan/run/run.go:63 +0xd0
kscan/run.scanMainSub(0xcb3d60, 0xce2bd0, 0xc006fe5030)
        /Users/kv2/Project/Gkscan/run/run.go:81 +0x173
kscan/run.scanMainSub(0xcb3d60, 0xce2bd0, 0xc006fe5030)
        /Users/kv2/Project/Gkscan/run/run.go:81 +0x173
kscan/run.scanMainSub(0xcb3d60, 0xce2bd0, 0xc006fe5030)
        /Users/kv2/Project/Gkscan/run/run.go:81 +0x173
kscan/run.scanMainSub(0xcb3d60, 0xce2bd0, 0xc006fe5030)
        /Users/kv2/Project/Gkscan/run/run.go:81 +0x173
kscan/run.scanMainSub(0xcb3d60, 0xce2bd0, 0xc006fe5030)
        /Users/kv2/Project/Gkscan/run/run.go:81 +0x173
kscan/run.scanMainSub(0xcb3d60, 0xce2bd0, 0xc006fe5030)
        /Users/kv2/Project/Gkscan/run/run.go:81 +0x173
kscan/run.scanMainSub(0xcb3d60, 0xce2bd0, 0xc006fe5030)
        /Users/kv2/Project/Gkscan/run/run.go:81 +0x173
kscan/run.scanMainSub(0xcb3d60, 0xce2bd0, 0xc006fe5030)
        /Users/kv2/Project/Gkscan/run/run.go:81 +0x173
kscan/run.scanMainSub(0xcb3d60, 0xce2bd0, 0xc006fe5030)
        /Users/kv2/Project/Gkscan/run/run.go:81 +0x173
kscan/run.scanMainSub(0xcb3d60, 0xce2bd0, 0xc006fe5030)
        /Users/kv2/Project/Gkscan/run/run.go:81 +0x173
kscan/run.scanMainSub(0xcb3d60, 0xce2bd0, 0xc006fe5030)
        /Users/kv2/Project/Gkscan/run/run.go:81 +0x173
kscan/run.scanMainSub(0xcb3d60, 0xce2bd0, 0xc006fe5030)
        /Users/kv2/Project/Gkscan/run/run.go:81 +0x173
kscan/run.scanMainSub(0xcb3d60, 0xce2bd0, 0xc006fe5030)
        /Users/kv2/Project/Gkscan/run/run.go:81 +0x173
kscan/run.scanMainSub(0xcb3d60, 0xce2bd0, 0xc006fe5030)
        /Users/kv2/Project/Gkscan/run/run.go:81 +0x173
kscan/run.scanMainSub(0xcb3d60, 0xce2bd0, 0xc006fe5030)
        /Users/kv2/Project/Gkscan/run/run.go:81 +0x173
kscan/run.scanMainSub(0xcb3d60, 0xce2bd0, 0xc006fe5030)
        /Users/kv2/Project/Gkscan/run/run.go:81 +0x173
kscan/run.scanMainSub(0xcb3d60, 0xce2bd0, 0xc006fe5030)
        /Users/kv2/Project/Gkscan/run/run.go:81 +0x173
kscan/run.scanMainSub(0xcb3d60, 0xce2bd0, 0xc006fe5030)
        /Users/kv2/Project/Gkscan/run/run.go:81 +0x173
kscan/run.scanMainSub(0xcb3d60, 0xce2bd0, 0xc006fe5030)
        /Users/kv2/Project/Gkscan/run/run.go:81 +0x173
kscan/run.scanMainSub(0xcb3d60, 0xce2bd0, 0xc006fe5030)
        /Users/kv2/Project/Gkscan/run/run.go:81 +0x173
kscan/run.scanMainSub(0xcb3d60, 0xce2bd0, 0xc006fe5030)
        /Users/kv2/Project/Gkscan/run/run.go:81 +0x173
kscan/run.scanMainSub(0xcb3d60, 0xce2bd0, 0xc006fe5030)
        /Users/kv2/Project/Gkscan/run/run.go:81 +0x173
kscan/run.scanMainSub(0xcb3d60, 0xce2bd0, 0xc006fe5030)
        /Users/kv2/Project/Gkscan/run/run.go:81 +0x173
kscan/run.scanMainSub(0xcb3d60, 0xce2bd0, 0xc006fe5030)
        /Users/kv2/Project/Gkscan/run/run.go:81 +0x173
kscan/run.scanMainSub(0xcb3d60, 0xce2bd0, 0xc006fe5030)
        /Users/kv2/Project/Gkscan/run/run.go:81 +0x173
kscan/run.scanMainSub(0xcb3d60, 0xce2bd0, 0xc006fe5030)
        /Users/kv2/Project/Gkscan/run/run.go:81 +0x173
kscan/run.scanMainSub(0xcb3d60, 0xce2bd0, 0xc006fe5030)
        /Users/kv2/Project/Gkscan/run/run.go:81 +0x173
kscan/run.scanMainSub(0xcb3d60, 0xce2bd0, 0xc006fe5030)
        /Users/kv2/Project/Gkscan/run/run.go:81 +0x173
kscan/run.scanMainSub(0xcb3d60, 0xce2bd0, 0xc006fe5030)
        /Users/kv2/Project/Gkscan/run/run.go:81 +0x173
kscan/run.scanMainSub(0xcb3d60, 0xce2bd0, 0xc006fe5030)
        /Users/kv2/Project/Gkscan/run/run.go:81 +0x173
kscan/run.scanMainSub(0xcb3d60, 0xce2bd0, 0xc006fe5030)
        /Users/kv2/Project/Gkscan/run/run.go:81 +0x173
kscan/run.scanMainSub(0xcb3d60, 0xce2bd0, 0xc006fe5030)
        /Users/kv2/Project/Gkscan/run/run.go:81 +0x173
kscan/run.scanMainSub(0xcb3d60, 0xce2bd0, 0xc006fe5030)
        /Users/kv2/Project/Gkscan/run/run.go:81 +0x173
kscan/run.scanMainSub(0xcb3d60, 0xce2bd0, 0xc006fe5030)
        /Users/kv2/Project/Gkscan/run/run.go:81 +0x173
kscan/run.scanMainSub(0xcb3d60, 0xce2bd0, 0xc006fe5030)
        /Users/kv2/Project/Gkscan/run/run.go:81 +0x173
kscan/run.scanMainSub(0xcb3d60, 0xce2bd0, 0xc006fe5030)
        /Users/kv2/Project/Gkscan/run/run.go:81 +0x173
kscan/run.scanMainSub(0xcb3d60, 0xce2bd0, 0xc006fe5030)
        /Users/kv2/Project/Gkscan/run/run.go:81 +0x173
kscan/run.scanMainSub(0xcb3d60, 0xce2bd0, 0xc006fe5030)
        /Users/kv2/Project/Gkscan/run/run.go:81 +0x173
kscan/run.scanMainSub(0xcb3d60, 0xce2bd0, 0xc006fe5030)
        /Users/kv2/Project/Gkscan/run/run.go:81 +0x173
kscan/run.scanMainSub(0xcb3d60, 0xce2bd0, 0xc006fe5030)
        /Users/kv2/Project/Gkscan/run/run.go:81 +0x173
kscan/run.scanMainSub(0xcb3d60, 0xce2bd0, 0xc006fe5030)
        /Users/kv2/Project/Gkscan/run/run.go:81 +0x173
kscan/run.scanMainSub(0xcb3d60, 0xce2bd0, 0xc006fe5030)
        /Users/kv2/Project/Gkscan/run/run.go:81 +0x173
kscan/run.scanMainSub(0xcb3d60, 0xce2bd0, 0xc006fe5030)
        /Users/kv2/Project/Gkscan/run/run.go:81 +0x173
kscan/run.scanMainSub(0xcb3d60, 0xce2bd0, 0xc006fe5030)
        /Users/kv2/Project/Gkscan/run/run.go:81 +0x173
kscan/run.scanMainSub(0xcb3d60, 0xce2bd0, 0xc006fe5030)
        /Users/kv2/Project/Gkscan/run/run.go:81 +0x173
kscan/run.scanMainSub(0xcb3d60, 0xce2bd0, 0xc006fe5030)
        /Users/kv2/Project/Gkscan/run/run.go:81 +0x173
created by kscan/run.scanMain
        /Users/kv2/Project/Gkscan/run/run.go:53 +0x110

**Comment by lcvvvv** [comment]
现在会对协程进行异常捕获，不会再出现单个协程崩溃而导致整个程序崩溃的情况了。
