### ISSUE TITLE
json输出格式问题 

### ISSUE THREAD

**Issue by liangjs** [lcvvvv/kscan#123]
reopen https://github.com/lcvvvv/kscan/issues/115

这个问题没有被 https://github.com/lcvvvv/kscan/pull/116 解决。

<img width="853" alt="WeChat Image_20221218195946" src="https://user-images.githubusercontent.com/10512425/208297206-125786d5-c082-4c4c-ba3f-de2ac612baff.png">

**Comment by lcvvvv** [comment]
加一下我微信，详细聊了聊
微信二维码见：#23
