### ISSUE TITLE
1.85重新打包编译-t参数接url形式会报错

### ISSUE THREAD

**Issue by andrewgogogo** [lcvvvv/kscan#127]
例如：-t参数后直接接url，会报错：
`kscan.exe -t https://www.baidu.com`
![报错](https://user-images.githubusercontent.com/91301016/211517507-ca117285-42cd-4af6-b16c-1b4080cbd107.jpg)

换一种形式是可以的，例如指定端口：
`kscan.exe -t www.baidu.com -p 443`

**Comment by lcvvvv** [comment]
![图片](https://user-images.githubusercontent.com/49975427/211954031-e647d31b-8f2e-4a3c-9b16-03eb01d850a1.png)

这个bug已经在最新版本修复，请下载最新版本，或自行编译

**Comment by andrewgogogo** [comment]
直接下载二进制运行是可以的，下载源代码压缩包编译之后就不行，是不是release中的源代码压缩包跟二进制文件不同步？

**Comment by lcvvvv** [comment]
直接git clone编译最新版本就行

release版本在中的源码压缩包确实可能存在这个bug

**Comment by andrewgogogo** [comment]
好的，谢谢
