### ISSUE TITLE
扫描ip列表只能读取第一行ip

### ISSUE THREAD

**Issue by badboycxcc** [lcvvvv/kscan#13]
自己有一个ip列表文件，扫描只能读取第一个ip。

----

[*]2021/05/25 09:20:31 > 开始读取扫描对象...
[+]2021/05/25 09:20:31 > 成功读取URL地址:[0]个
[+]2021/05/25 09:20:31 > 成功读取主机地址:[1]个，待检测端口:[400]个
[+]2021/05/25 09:20:31 > 成功加载favicon指纹:[493]条，keyword指纹:[1323]条
[+]2021/05/25 09:20:35 > 成功加载NMAP探针:[148]个,指纹[11885]条
[*]2021/05/25 09:20:35 > 本次扫描将使用NMAP探针:[28]个,指纹[11209]条
[*]2021/05/25 09:20:35 > 开始压入URL地址队列...
[*]2021/05/25 09:20:35 > 本次需要直接扫描的URL地址共:[0]个。...
[*]2021/05/25 09:20:35 > 本次需扫描主机IP地址共:[1]个...
[*]2021/05/25 09:20:35 > 开始压入端口扫描队列...
[*]2021/05/25 09:20:36 > 开始扫描所有开放端口,总协程数为：[0]...

**Comment by lcvvvv** [comment]
已更新，问题应该已经解决
