### ISSUE TITLE
是越界了吗？

### ISSUE THREAD

**Issue by teamtopkarl** [lcvvvv/kscan#14]
panic: runtime error: index out of range [10] with length 10

goroutine 1 [running]:
kscan/lib/chinese.isUtf8(0xc0052b7b40, 0xa, 0x10, 0xc0052b7b4a)
        /Users/kv2/Project/Gkscan/lib/chinese/chinese.go:83 +0xed
kscan/lib/chinese.ByteToUTF8(0xc0052b7b40, 0xa, 0x10, 0xc0052b7b40, 0xa, 0x10)
        /Users/kv2/Project/Gkscan/lib/chinese/chinese.go:32 +0x61
kscan/lib/chinese.ToUTF8(...)
        /Users/kv2/Project/Gkscan/lib/chinese/chinese.go:63
kscan/lib/gonmap.(*AppBanner).Output(0xc003c492c0, 0xc0004cbd40, 0x1)
        /Users/kv2/Project/Gkscan/lib/gonmap/type-appbanner.go:176 +0xa8
kscan/run.(*kscan).Output(0xc008248b40)
        /Users/kv2/Project/Gkscan/run/type-kscan.go:215 +0x9a
kscan/run.Start(0xc000192000, 0xff, 0x100, 0xce8998, 0x0, 0x0, 0xc4e800, 0x190, 0x462, 0x0, ...)
        /Users/kv2/Project/Gkscan/run/run.go:37 +0x1f0
main.main()
        /Users/kv2/Project/Gkscan/kscan.go:59 +0x8b

**Comment by teamtopkarl** [comment]
一开始扫C段就这样

**Comment by lcvvvv** [comment]
这个是一个点写错了，现在的源码已经解决，但是懒得再发布了，你可以自己编译一个，可以进群我发最新版本给你

**Comment by teamtopkarl** [comment]
微信多少，群号多少？------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年6月17日(星期四) 下午4:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lcvvvv/kscan] 是越界了吗？ (#14)

**Comment by lcvvvv** [comment]
README最后面有
