### ISSUE TITLE
linux下有bug

### ISSUE THREAD

**Issue by xiaoliangli1128** [lcvvvv/kscan#142]
如图同一个目标ip，windows可以扫到，linux却扫不到端口
![图片](https://user-images.githubusercontent.com/66862331/226798862-134b6306-b18e-4a86-8248-9fbae7500a66.png)

**Comment by wwj-saber** [comment]
我也遇到了这个问题 windows上可以扫的到，vps上扫不到

**Comment by wwj-saber** [comment]
> 通的呢。用nmap和fscan测试可以扫到

请问你这个最后解决了吗
