### ISSUE TITLE
最新版的ip正则好像有些问题

### ISSUE THREAD

**Issue by nannanshen** [lcvvvv/kscan#16]
![捕获](https://user-images.githubusercontent.com/28394081/123195673-29d9d480-d4db-11eb-8282-0d04c0d3d376.PNG)

**Comment by lcvvvv** [comment]
你是自己编译的？现在这个问题已经解决了，你重新下载下源码再编译一下就可以了

**Comment by nannanshen** [comment]
> 你是自己编译的？现在这个问题已经解决了，你重新下载下源码再编译一下就可以了

这个问题解决了，谢谢大佬。还发现一个问题，读取文件的时候读不到第一行的内容。
![捕获](https://user-images.githubusercontent.com/28394081/123199967-74ab1a80-d4e2-11eb-9402-996cc7c0409b.PNG)
