### ISSUE TITLE
使用-t参数从文件读取地址时出现bug

### ISSUE THREAD

**Issue by theLSA** [lcvvvv/kscan#17]
release v1.25 windows
使用-t参数从文件读取地址时出现bug
![kscan-issue-2021-07-03_15-12](https://user-images.githubusercontent.com/28248956/124346456-79be4700-dc11-11eb-9bf8-9c8ecaca4a62.png)

**Comment by lcvvvv** [comment]
要加file:前缀

**Comment by wenyurush** [comment]
同样的问题，file: 加相对路径，绝对路径，都没法办法扫描

**Comment by lcvvvv** [comment]
加微信看看发下具体情况给我看看
