### ISSUE TITLE
高亮整一个？

### ISSUE THREAD

**Issue by lapalipi** [lcvvvv/kscan#19]
观赏度不是太好，来个高亮？

**Comment by lcvvvv** [comment]
后期会加，但是现在没啥好解决方案兼容多种终端

**Comment by lcvvvv** [comment]
<img width="896" alt="图片" src="https://user-images.githubusercontent.com/49975427/129540689-442a12c3-82a0-4e2c-8f60-c65f6ad241d5.png">
它Lei了~
