### ISSUE TITLE
使用-o 生成的.txt：文本编码Unicode (UTF-8)不适用。

### ISSUE THREAD

**Issue by ThestaRY7** [lcvvvv/kscan#2]
![image](https://user-images.githubusercontent.com/48352738/108598741-52857c80-73ca-11eb-9b99-1fee6df7869f.png)

**Comment by lcvvvv** [comment]
这个问题正在逐步解决，成因是因为部分网页使用的是gbk2312，在转换成utf-8时编码不正确导致

**Comment by lcvvvv** [comment]
现在这个问题应该已经解决。
