### ISSUE TITLE
可以提供一下，自行编译的操作步骤吗？

### ISSUE THREAD

**Issue by r0ckysec** [lcvvvv/kscan#25]
遇到好多坑
![image](https://user-images.githubusercontent.com/44518337/128963272-4d9f7668-9dea-40ea-9f23-b8ab4447215d.png)
特别是 编译中的 hydra 模块的编译，一直没有编译成功

**Comment by lcvvvv** [comment]
现在编译应该会非常简单，已经不再使用freerdp了
