### ISSUE TITLE
-f  参数问题

### ISSUE THREAD

**Issue by XMTongXie** [lcvvvv/kscan#27]
使用 -f  参数的时候，好像不能同时执行 多条fofa语句，比如这个
![图片](https://user-images.githubusercontent.com/64581233/135370505-9d52f9db-7f13-40f5-9acf-a82a4995b363.png)

**Comment by lcvvvv** [comment]
这个是终端的问题，因为你没有对&符号做转义处理
你可以使用
`\&`

或者使用单引号把语句包括起来
