### ISSUE TITLE
2003 2008 不能正常使用

### ISSUE THREAD

**Issue by shmilylty** [lcvvvv/kscan#28]
![image](https://user-images.githubusercontent.com/24275308/138386941-df4e6fc4-bde2-46aa-8524-06b2858fa2d4.png)

**Comment by lcvvvv** [comment]
确实有这个问题，我也很头痛，目前还无法解决，需要一个C语言大佬

**Comment by lcvvvv** [comment]
现在这个问题应该已经解决了，丢弃之前使用的cgo解决方案
