### ISSUE TITLE
能否写个使用的详细例子文本

### ISSUE THREAD

**Issue by ttsite** [lcvvvv/kscan#29]
能否发个详细的使用例子文本利如MYSSQL批定ip段txt文件。指定端口。指定用户名和密典的爆破文本.谢谢!

**Comment by lcvvvv** [comment]
kscan -t file:/tmp/target.txt -p 33306 --hydra --hydra-mod mysql --hydra-user root --hydra-pass file:/tmp/mysql_pass.dic
