### ISSUE TITLE
扫描端口问题小记

### ISSUE THREAD

**Issue by passtion** [lcvvvv/kscan#3]
扫描端口问题小记：
1、**未存活的主机扫描出25端口**，**建议增加存活检测参数**；
2、**扫描滚动显示存在多余显示问题**，速度过快还会显示端口大于65535的情况，如：
cmd窗口显示：
[+]192.168.1.19:25	stmp,25
[+]192.168.1.13:25	stmp,25情况：192.168.1.47:90028
[+]192.168.1.24:25	stmp,25
[+]192.168.1.23:25	stmp,25
[+]192.168.1.15:25	stmp,25
[+]192.168.1.20:25	stmp,25情况：192.168.1.49:80849
[+]192.168.1.14:25	stmp,25情况：192.168.1.43:80800
[+]192.168.1.11:25	stmp,25
[+]192.168.1.8:25	stmp,25情况：192.168.1.49:11005

cmder窗口显示：
[+]192.168.1.49:25    ：401]正在测试端口：192.168.1.49:49705
[+]192.168.1.50:25	stmp,25
[+]192.168.1.51:25	stmp,25
[+]192.168.1.52:25    ：401]正在测试端口：192.168.1.53:54325
[+]192.168.1.53:25	stmp,25
[+]192.168.1.54:25	stmp,25
[+]192.168.1.55:25	stmp,25
[+]192.168.1.55:25	stmp,25
[+]192.168.1.56:25	stmp,25
[+]192.168.1.57:25	stmp,25
[+]192.168.1.58:25    ：401]正在测试端口：192.168.1.59:81800
[+]192.168.1.59:25    ：401]正在测试端口：192.168.1.60:8082
[+]192.168.1.60:25	stmp,25
[+]192.168.1.61:25	stmp,25
[+]192.168.1.62:25    ：401]正在测试端口：192.168.1.63:1350
[+]192.168.1.63:25    ：401]正在测试端口：192.168.1.63:50805

**Comment by lcvvvv** [comment]
理论上不应该会出现未存活主机出现扫描出25端口的情况，因为端口开放的判断逻辑是tcp连接建立成功，才会打印显示端口开放。可否提供更详细的截图。
至于滚动显示多余问题，这个正在逐步解决。

**Comment by lcvvvv** [comment]
现在不会存在这种问题了。
