### ISSUE TITLE
-f参数无效

### ISSUE THREAD

**Issue by sodmelody** [lcvvvv/kscan#31]
已填写fofa key编译使用发现，-f参数失效
![image](https://user-images.githubusercontent.com/29257678/145248123-d4bf96c7-a48e-4d51-8c1c-56e296552913.png)

**Comment by lcvvvv** [comment]
fofakey怎么配置的？
export FOFA_EMAIL=cemail@gmail.com
export FOFA_KEY=xxxx
是这样吗？出现这种情况一般是配置错了

**Comment by sodmelody** [comment]
> fofakey怎么配置的？ export FOFA_EMAIL=[cemail@gmail.com](mailto:cemail@gmail.com) export FOFA_KEY=xxxx 是这样吗？出现这种情况一般是配置错了

应该是配置错误吧，我是直接硬编码到代码里面，然后编译的。

**Comment by sodmelody** [comment]
> 那你应该代码改错了，尝试环境变量配置试一下

对的，感谢。

**Comment by zzqsmile** [comment]
怎么配置fofa key，
