### ISSUE TITLE
无法探测操作系统类型？

### ISSUE THREAD

**Issue by ismlsmile** [lcvvvv/kscan#32]

**Comment by lcvvvv** [comment]
目前确实没有这个功能，感觉比较鸡肋，效率也比较低，所以没有做

**Comment by ismlsmile** [comment]
功能有用，并不鸡肋。但效率、准确性确实是个问题，nmap的效果也并不好

**Comment by lcvvvv** [comment]
我感觉没啥场景是一定要知道操作系统类型的呀，或者换句话说是没啥场景，一定要在扫描这个阶段就需要知道操作系统类型的呀

**Comment by ismlsmile** [comment]
好吧
