### ISSUE TITLE
内存崩溃

### ISSUE THREAD

**Issue by r0ckysec** [lcvvvv/kscan#34]
之前跑50万子域名的时候，内存不足会崩溃，后面会考虑优化吗？
最近我自己也在尝试优化，优化了60%，不过最后还是崩溃了，目前发现主要是AppBanner那边存储了响应内容不断累积导致的

![image](https://user-images.githubusercontent.com/44518337/147551699-bb56733a-604e-411c-bb0d-79c35ff7d577.png)

**Comment by lcvvvv** [comment]
。。。。。。。。暂时还没考虑这么大量级的扫描，存储响应内容是为了便于后续一些其他的考虑，
后续肯定会优化的，只是不是优先解决的问题
要是实在需要做大资产扫描，暂时只能分批，或者扩内存了

**Comment by r0ckysec** [comment]
好的了解
