### ISSUE TITLE
1.53.1-1.60版本登录爆破模块存在BUG

### ISSUE THREAD

**Issue by winezer0** [lcvvvv/kscan#35]
1.53.1版本识别服务成功后没有调用爆破
![image](https://user-images.githubusercontent.com/46115146/148714562-f962130f-32d5-4e47-845a-f5f23446a772.png)

1.60.0版本识别服务调用爆破模块后没有爆破成功，手工测试登录成功（已知redis密码进行测试）

更早版本未测试，fscan扫描redis口令成功

使用命令
./kscan_linux_amd64 -t XXXX -p  6379 -o result.txt   --hydra  --hydra-pass  pass.txt  
 ./kscan_linux_amd64 -t  XXXX -p  6379 -o result.txt   --hydra  --hydra-pass  pass.txt  --hydra-mod redis

**Comment by lcvvvv** [comment]
这个是弱口令，还是空口令？

看你这个截图，应该不是1.6版本扫的呀

**Comment by lcvvvv** [comment]
然后你命令错了，要用
--hydra-pass file:pass.txt

**Comment by winezer0** [comment]
--hydra-pass file:pass.txt 这个却是没有用，用的--hydra-pass pass.txt。

截图时1.53.1版本的，1.60没截图。我再试试

**Comment by winezer0** [comment]
![image](https://user-images.githubusercontent.com/46115146/148718215-1b8a72f9-baf8-4985-8145-84589962eb63.png)
1.53.1版本使用--hydra-pass file:pass.txt 进行测试 无结果。

**Comment by winezer0** [comment]
![image](https://user-images.githubusercontent.com/46115146/148718793-718dee71-ffdd-482b-b65f-701cd2de74b6.png)
1.60 版本使用--hydra-pass file:pass.txt （无图），--hydra-pass xxxxx （上图）进行测试 。
--hydra-pass参数读取的本来是密码字典，却在redis上加进了用户名列表

**Comment by lcvvvv** [comment]
你加update参数，会在原有字典上新增，但是也应该是可以出来的，方便加我发下资产吗

**Comment by winezer0** [comment]
OK ,我的WX是winezer0
