### ISSUE TITLE
暴力破解问题

### ISSUE THREAD

**Issue by ketchup1995** [lcvvvv/kscan#37]
请问指定协议爆破是这样使用吗
`kscan_64.exe -t ip -Pn --hydra-mod ssh`
为什么我指定协议不会去爆破ssh
![图片](https://user-images.githubusercontent.com/87350553/148882729-4a1d9347-9f97-4cdb-a2a3-abb8f1ce7a28.png)
然后不指定协议就会去爆破ssh
`kscan_64.exe -t ip -Pn --hydra`
![图片](https://user-images.githubusercontent.com/87350553/148883004-62955343-ba94-4303-8dbf-758be9bad8a0.png)

**Comment by lcvvvv** [comment]
--hydra 参数是开关，必须带这个参数才会进行暴力破解


--hydra-mod是修饰，默认是所有协议都会进行暴力破解的，你可以只指定只针对某一种协议进行暴力破解

**Comment by ketchup1995** [comment]
> --hydra 参数是开关，必须带这个参数才会进行暴力破解
> 
> --hydra-mod是修饰，默认是所有协议都会进行暴力破解的，你可以只指定只针对某一种协议进行暴力破解

这不是带了吗，指定协议是这样指定吗？
kscan_64.exe -t ip -Pn --hydra-mod ssh
kscan_64.exe -t ip -Pn --hydra

**Comment by lcvvvv** [comment]
kscan_64.exe -t ip -Pn --hydra  --hydra-mod ssh
