### ISSUE TITLE
扫描报错

### ISSUE THREAD

**Issue by teamtopkarl** [lcvvvv/kscan#39]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x13352f3]

goroutine 110 [running]:
kscan/run.(*kscan).GetTcpBanner.func3(0xc0086f2d80)
        D:/scan/kscan/kscan/run/type-kscan.go:262 +0xb3
created by kscan/run.(*kscan).GetTcpBanner
        D:/scan/kscan/kscan/run/type-kscan.go:256 +0xb5

**Comment by lcvvvv** [comment]
新版本已修复
