### ISSUE TITLE
linux 遇到错误

### ISSUE THREAD

**Issue by badboycxcc** [lcvvvv/kscan#41]
错误太多了，以这种为主

goroutine 1594 [chan receive, 50 minutes]:
kscan/lib/pool.(*Pool).work(0xc004e5def0)
        /Users/kv2/Project/Gkscan/lib/pool/pool.go:81 +0x94
created by kscan/lib/pool.(*Pool).Run
        /Users/kv2/Project/Gkscan/lib/pool/pool.go:110 +0x79

goroutine 1595 [chan send]:
kscan/lib/pool.(*Pool).work(0xc004e5df90)
        /Users/kv2/Project/Gkscan/lib/pool/pool.go:96 +0x265
created by kscan/lib/pool.(*Pool).Run
        /Users/kv2/Project/Gkscan/lib/pool/pool.go:110 +0x79

中间伴随着少量这种错误

goroutine 2938 [runnable]:
internal/poll.runtime_pollWait(0x7fbf2b8c8ac0, 0x77, 0xc004ce8000)
        /Users/kv2/Project/go/go1.16.10/src/runtime/netpoll.go:227 +0x55
internal/poll.(*pollDesc).wait(0xc004923e98, 0x77, 0x103f600, 0xc0052285a0, 0xc004923e80)
        /Users/kv2/Project/go/go1.16.10/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitWrite(...)
        /Users/kv2/Project/go/go1.16.10/src/internal/poll/fd_poll_runtime.go:96
internal/poll.(*FD).WaitWrite(...)
        /Users/kv2/Project/go/go1.16.10/src/internal/poll/fd_unix.go:528
net.(*netFD).connect(0xc004923e80, 0x103f6c8, 0xc0052285a0, 0x0, 0x0, 0x1033bc0, 0xc003616680, 0x0, 0x0, 0x0, ...)
        /Users/kv2/Project/go/go1.16.10/src/net/fd_unix.go:141 +0x27b
net.(*netFD).dial(0xc004923e80, 0x103f6c8, 0xc0052285a0, 0x1042c50, 0x0, 0x1042c50, 0xc00a6f06c0, 0x0, 0x7fbf2aa48ed8, 0x10)
        /Users/kv2/Project/go/go1.16.10/src/net/sock_posix.go:149 +0x10b
net.socket(0x103f6c8, 0xc0052285a0, 0xc39a52, 0x3, 0x2, 0x1, 0x0, 0x0, 0x1042c50, 0x0, ...)
        /Users/kv2/Project/go/go1.16.10/src/net/sock_posix.go:70 +0x1c5
net.internetSocket(0x103f6c8, 0xc0052285a0, 0xc39a52, 0x3, 0x1042c50, 0x0, 0x1042c50, 0xc00a6f06c0, 0x1, 0x0, ...)
        /Users/kv2/Project/go/go1.16.10/src/net/ipsock_posix.go:141 +0x145
net.(*sysDialer).doDialTCP(0xc004923b80, 0x103f6c8, 0xc0052285a0, 0x0, 0xc00a6f06c0, 0xb7b7e0, 0x18aaf98, 0x0)
        /Users/kv2/Project/go/go1.16.10/src/net/tcpsock_posix.go:65 +0xc5
net.(*sysDialer).dialTCP(0xc004923b80, 0x103f6c8, 0xc0052285a0, 0x0, 0xc00a6f06c0, 0x46bcc7, 0x4055fd, 0x60)
        /Users/kv2/Project/go/go1.16.10/src/net/tcpsock_posix.go:61 +0xd7
net.(*sysDialer).dialSingle(0xc004923b80, 0x103f6c8, 0xc0052285a0, 0x1038b40, 0xc00a6f06c0, 0x0, 0x0, 0x0, 0x0)
        /Users/kv2/Project/go/go1.16.10/src/net/dial.go:580 +0x5e8
net.(*sysDialer).dialSerial(0xc004923b80, 0x103f6c8, 0xc0052285a0, 0xc013ccd2a0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
        /Users/kv2/Project/go/go1.16.10/src/net/dial.go:548 +0x15e
net.(*Dialer).DialContext(0xc009bffc90, 0x103f6c8, 0xc0052285a0, 0xc39a52, 0x3, 0xc00ae4ce70, 0x13, 0x0, 0x0, 0x0, ...)
        /Users/kv2/Project/go/go1.16.10/src/net/dial.go:425 +0x6e5
net.(*Dialer).Dial(...)
        /Users/kv2/Project/go/go1.16.10/src/net/dial.go:348
net.DialTimeout(0xc39a52, 0x3, 0xc00ae4ce70, 0x13, 0xb2d05e00, 0x40dbd2, 0x7fbf2af59f40, 0xc00ae4ce70, 0x18)
        /Users/kv2/Project/go/go1.16.10/src/net/dial.go:334 +0xba
kscan/lib/gonmap/simplenet.Send(0xc39a52, 0x3, 0xc00ae4ce70, 0x13, 0x0, 0x0, 0xb2d05e00, 0x0, 0x0, 0x0, ...)
        /Users/kv2/Project/Gkscan/lib/gonmap/simplenet/simplenet.go:14 +0xaf
kscan/lib/gonmap.PortScan(0xc39a52, 0x3, 0xc00ae4ce70, 0x13, 0xb2d05e00, 0xc00ae4ce70)
        /Users/kv2/Project/Gkscan/lib/gonmap/portscan.go:12 +0x71
kscan/run.(*kscan).PortDiscovery.func3(0xbde220, 0xc007c7d240, 0x124, 0x1)
        /Users/kv2/Project/Gkscan/run/type-kscan.go:225 +0x14f
kscan/lib/pool.NewWorker.func1(0xbde220, 0xc007c7d240, 0x0, 0x0, 0x0, 0x0)
        /Users/kv2/Project/Gkscan/lib/pool/pool.go:28 +0x82
kscan/lib/pool.(*Worker).Run(...)
        /Users/kv2/Project/Gkscan/lib/pool/pool.go:36
kscan/lib/pool.(*Pool).work(0xc004e5df90)
        /Users/kv2/Project/Gkscan/lib/pool/pool.go:92 +0x185
created by kscan/lib/pool.(*Pool).Run
        /Users/kv2/Project/Gkscan/lib/pool/pool.go:110 +0x79

**Comment by lcvvvv** [comment]
版本是多少？

**Comment by lcvvvv** [comment]
加我微信看看吧

**Comment by badboycxcc** [comment]
有你微信
