### ISSUE TITLE
Bug：不能识别ip:port文本

### ISSUE THREAD

**Issue by okoling** [lcvvvv/kscan#42]
命令：`./kscan -t file:./url.txt  --check`
不能识别ip:port格式

url.txt
```
1.1.1.1:8210
2.2.2.2:8014
```

只提取了一些文件中的 `:80`去识别

**Comment by lcvvvv** [comment]
最新版本试试

**Comment by okoling** [comment]
暂时没编译环境直接下载的Releases，发现没更新到最新版，劳烦编译一下~

**Comment by okoling** [comment]
> 最新版本试试

也不能有效探测ip:555这类端口

**Comment by lcvvvv** [comment]
确实有这个问题，等有空来改这个bug

**Comment by lcvvvv** [comment]
修了修了，之前代码逻辑有问题

**Comment by lcvvvv** [comment]
最新代码编译下康康
