### ISSUE TITLE
linux下必须root才能跑

### ISSUE THREAD

**Issue by 3as0n** [lcvvvv/kscan#43]
![微信截图_20220302194537](https://user-images.githubusercontent.com/8120951/156356922-004982f2-2092-4563-8190-23b2571eaeca.png)

**Comment by lcvvvv** [comment]
目前确实是这样，后续会想办法解决这个问题

**Comment by lcvvvv** [comment]
试一试，现在使用操作系统进行ping检测，低权限也可以用了~

**Comment by 3as0n** [comment]
好的师傅

**Comment by 3as0n** [comment]
师傅可以扫描了
