### ISSUE TITLE
如何扫描指定列表的端口内容

### ISSUE THREAD

**Issue by ttsite** [lcvvvv/kscan#50]
假如我有个ip.txt里面是扫描好的3389或者1433 。如何调用这个指定的ip.txt和批定的user.txt和pass.txt进行指定端口的爆破。请问完整格式是什么谢谢

**Comment by lcvvvv** [comment]
-t file:/path/to/list.txt --check  --hydra --hydra-user file:/path/to/user.txt --hydra-pass file:/path/to/pass.txt
