### ISSUE TITLE
大佬，提个需求，在接受主机输入的时候能否识别一下cdn做个判断。

### ISSUE THREAD

**Issue by Curta7n** [lcvvvv/kscan#51]

**Comment by lcvvvv** [comment]
这个一直想做，但是一直没有一个高效的好思路，有啥案例灭有

**Comment by Curta7n** [comment]
现在好像常见的做法应该是通过离线ip库进行查询然后判定的，类似这种的。[https://github.com/zu1k/nali](url)

**Comment by lcvvvv** [comment]
这个思路确实可以，但是不便携，所以一直再找其他更好的方法

**Comment by lcvvvv** [comment]
试下v1.72新版本，做个简陋的识别，更精准存在较高的时效性，不适合kscan的定位了~

**Comment by Curta7n** [comment]
强呀大佬。去试试啦。
