### ISSUE TITLE
大量ip段内存占用特别大！

### ISSUE THREAD

**Issue by span5201** [lcvvvv/kscan#57]
30KB ip段内存占用达到6个GB

**Comment by span5201** [comment]
600W ip

**Comment by lcvvvv** [comment]
占用内存大是正常的，因为要保存body段，存到json，扫描结束之后才会写入到文件中，所以内存会一直增加。
大网段的扫描，建议分段扫，以后会想办法改掉json这个逻辑，但目前没有更好的办法

**Comment by lcvvvv** [comment]
最新版本的内存占用应该有所改善，你试试看

**Comment by wycdavid** [comment]
> 占用内存大是正常的，因为要保存body段，存到json，扫描结束之后才会写入到文件中，所以内存会一直增加。 大网段的扫描，建议分段扫，以后会想办法改掉json这个逻辑，但目前没有更好的办法

关于json输出的逻辑，可以提供一个思路，不一定非要等全部扫描完了再输出一个完整的json数组，可以考虑每一行输出一个json对象，这样就可以做到即时输出，也没有内存的负担。尤其是大批量扫描的时候。
