### ISSUE TITLE
配置fofa的email和key文件在哪个路径下呢？

### ISSUE THREAD

**Issue by Bergain** [lcvvvv/kscan#59]

**Comment by lcvvvv** [comment]
配置环境变量即可

**Comment by Bergain** [comment]
这个具体怎么配呢，别的工具都是有个配置文件把email和key填进去然后运行就可以用了，这个我还不知道具体怎么弄。

**Comment by Bergain** [comment]
具体怎么配置呢，可以发个操作说明吗，这个我还真不会，之前用别的一些工具都是有个配置文件里面把email和key填进去就好了。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Kv2 ***@***.***&gt;
发送时间: 2022年5月5日 16:48
收件人: lcvvvv/kscan ***@***.***&gt;
抄送: Bergain ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [lcvvvv/kscan] 配置fofa的email和key文件在哪个路径下呢？ (Issue #59)





 
Closed #59.

**Comment by lcvvvv** [comment]
https://jingyan.baidu.com/article/47a29f24610740c0142399ea.html

https://www.cnblogs.com/youyoui/p/10680329.html

**Comment by Bergain** [comment]
👌，多谢！

**Comment by Chinakentgao** [comment]
> 👌，多谢！
我知道怎么配置环境变量，问题是配置里面要怎么写看不懂。可否解答一下

**Comment by Xiufei-x** [comment]
师傅，mac 配置环境变量格式就是FOFA_EMAIL=“xxx”这样是么，
