### ISSUE TITLE
ARM版本程序执行失败

### ISSUE THREAD

**Issue by zhouhaocheng** [lcvvvv/kscan#62]
环境如下：

![kscan截图](https://user-images.githubusercontent.com/31977621/168939366-5a5792b5-c86b-497b-90e3-ae5025114af3.png)

请问是什么原因呢？

**Comment by lcvvvv** [comment]
你这个不是arm架构的操作系统吧

**Comment by lcvvvv** [comment]
uname -m
看一下

**Comment by zhouhaocheng** [comment]
![image](https://user-images.githubusercontent.com/31977621/168949690-47108f54-de29-4dd4-8b6b-b667ab8b8df6.png)

是arm架构的，在阿里云上启动的一台实例

![image](https://user-images.githubusercontent.com/31977621/168949749-aaefc566-12af-42b2-8431-ef3f5b8a8e5b.png)

**Comment by lcvvvv** [comment]
本地编译一下吧
