### ISSUE TITLE
请问每个任务执行了一段时间后最后都显示killed是正常的吗

### ISSUE THREAD

**Issue by wycdavid** [lcvvvv/kscan#63]
请问是正常的吗？另外两个参数 -o result.txt 和-oJ result.json 可以同时使用吗

**Comment by lcvvvv** [comment]
Kill的不正常，资产多少，参数是什么？是不是内存超标了？

可以同时使用

**Comment by wycdavid** [comment]
我查了系统监测，应该是内存不够被系统自动杀掉了，1000个资产，4G的内存。。请问怎么才能节约内存，我下了源码，把response的输出注释掉，重新编译了。response不输出了，但是内存还是占用很大。

> 

我查了系统监测，应该是内存不够被系统自动杀掉了，1000个资产，4G的内存。。请问怎么才能节约内存，我下了源码，把response的输出注释掉，重新编译了。response不输出了，但是内存还是占用很大。

**Comment by wycdavid** [comment]
> Kill的不正常，资产多少，参数是什么？是不是内存超标了？
> 
> 可以同时使用

我查了系统监测，应该是内存不够被系统自动杀掉了，1000个资产，4G的内存。。请问怎么才能节约内存，我下了源码，把response的输出注释掉，重新编译了。response不输出了，但是内存还是占用很大。

**Comment by lcvvvv** [comment]
目前只能分批次扫描，现在的策略是会存内存里面,要改的话，你只能手工把gomap的返回结果里面的response改成空

**Comment by lcvvvv** [comment]
内存占用过大的问题，在最新版本应该已经解决，可以测试一下
