### ISSUE TITLE
是否可以支持IP:PORT

### ISSUE THREAD

**Issue by xming-dot** [lcvvvv/kscan#66]
kscan全端口的扫描速度相对于masscan和zmap来说比较慢，那么能不能将masscan扫描出来的开放端口放入到kscan中进行服务探测和指纹识别呢？kscan是否能够支持taget中识别IP:PORT这样的资产呢？

**Comment by lcvvvv** [comment]
支持，使用-check参数，就不会额外进行端口扫描，只会对给定的资产进行验证

kscan -t /path/to/ip-port.txt --check

**Comment by xming-dot** [comment]
好的，非常感谢
