### ISSUE TITLE
fofa 无法获取数据

### ISSUE THREAD

**Issue by 0xxtoby** [lcvvvv/kscan#74]
版本v1.76
已经配置好环境变量:FOFA_EMAIL、FOFA_KEY，可是没有返回数据

**Comment by Nixiabing** [comment]
同问，环境变量加了没效果
![image](https://user-images.githubusercontent.com/20591728/177022744-fa404697-b734-4be8-8fc8-88deaf2a2332.png)

**Comment by lcvvvv** [comment]
<img width="935" alt="图片" src="https://user-images.githubusercontent.com/49975427/177024253-79584193-88c4-4b8f-ba70-173fe0ff2d24.png">
key 是否设置有误？

**Comment by 0xxtoby** [comment]
对了请问fofa api 是不是要充值的啊 是不是不能免费用

**Comment by lcvvvv** [comment]
是的
