### ISSUE TITLE
The filename, directory name, or volume label syntax is incorrect

### ISSUE THREAD

**Issue by flyballon** [lcvvvv/kscan#76]
.\kscan_windows_amd64.exe -t https://www.test.com
无法运行，报错：
Error:https://www.test.comopen https://www.test.com: The filename, directory name, or volume label syntax is incorrect.

**Comment by lcvvvv** [comment]
是有这个问题，正则写错了
目前使用你可以把https://去掉，会自动识别协议。

**Comment by flyballon** [comment]
👌好的，谢谢！

在 2022年7月7日星期四，Kv2 ***@***.***> 写道：

**Comment by lcvvvv** [comment]
最新版本应该已经解决，可自行编译
