### ISSUE TITLE
程序不终止

### ISSUE THREAD

**Issue by TerickJojo** [lcvvvv/kscan#83]
3W+资产，扫描爆破完一直不终止，已经持续一个半小时
![image](https://user-images.githubusercontent.com/24235319/179184897-3f7ee080-3f38-499e-8e5a-efb326c36db2.png)
![image](https://user-images.githubusercontent.com/24235319/179185073-175e933f-7034-4e90-9aac-7be25a38059f.png)

**Comment by TerickJojo** [comment]
能不能先考虑在最后加个超时判定强行终止

**Comment by lcvvvv** [comment]
这个问题在最新版本，应该已经解决
