### ISSUE TITLE
指定文件后没有扫描

### ISSUE THREAD

**Issue by ybdt** [lcvvvv/kscan#85]
![image](https://user-images.githubusercontent.com/65813455/179665026-b5496805-3118-489b-94a6-240cc242d3b1.png)
如图，指定文件后，没有扫描就退出了

**Comment by lcvvvv** [comment]
确实有这个问题，但是我特么还没找到到原因

**Comment by tgirl7** [comment]
格式不对吧，

-t , --target   指定探测对象：
                  IP地址：114.114.114.114
                  IP地址段：114.114.114.114/24,不建议子网掩码小于12
                  IP地址段：114.114.114.114-115.115.115.115
                  URL地址：https://www.baidu.com
                  **文件地址：file:/tmp/target.txt**

**Comment by lcvvvv** [comment]
现在，也可以不加file:了

**Comment by lcvvvv** [comment]
试一试这个问题在，在最新版本是否解决
