### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by murray-sky** [lcvvvv/kscan#89]
在git clone 之后使用go mod tidy 提示：
go: github.com/lcvvvv/gonmap@v1.1.8 (replaced by ../gonmap): reading ../gonmap/go.mod: open /Users/xxxx/tools/gonmap/go.mod: no such file or directory
go: github.com/lcvvvv/gonmap@v1.1.8 (replaced by ../gonmap): reading ../gonmap/go.mod: open /Users/xxxx/tools/gonmap/go.mod: no such file or directory

**Comment by lcvvvv** [comment]
忘记push了，重新clone一下
