### ISSUE TITLE
-o输出格式可以选么

### ISSUE THREAD

**Issue by bycimi** [lcvvvv/kscan#9]
在进行大批量的扫描时可能xlsx或csv格式的文件更方便进行结果整理

**Comment by lcvvvv** [comment]
暂时不可以，之前有考虑写，还没想好咋分类，列太多了反而更不好整理

**Comment by hi-KK** [comment]
现在输出txt，可以自己手动导入表格嘛，多一步手动，少些代码逻辑，省心

**Comment by lcvvvv** [comment]
现在优化了输出格式，现在应该比较好编辑了
