### ISSUE TITLE
redis服务识别失败

### ISSUE THREAD

**Issue by u1timate06** [lcvvvv/kscan#95]
使用程序获取banner信息时发现redis服务无法识别成功。调试发现是正则的问题
```bash
[gonmap] 2022/08/16 14:40:40 type-probe.go:82: 开始匹配正则： service:redis 
pattern: ^-ERR wrong number of arguments for 'get' command\r\n$ 
response:-ERR wrong number of arguments for 'get' command
-ERR unknown command 'User-Agent:'
-ERR unknown command 'Accept:'
```
把正则改为`^-ERR wrong number of arguments for 'get' command\r\n`就可以正常识别，不知道其他服务有没有类似的情况。
扫描的redis服务版本: 3.2.12

**Comment by lcvvvv** [comment]
按理应该不会，资产方便加我微信发一下吗？

**Comment by lcvvvv** [comment]
<img width="825" alt="图片" src="https://user-images.githubusercontent.com/49975427/184820752-da7fd8ed-d9ce-40ff-8a06-8424cafceac7.png">

**Comment by lcvvvv** [comment]
已优化指纹库，最新版源码，编译后，应该能够正常识别
