### ISSUE TITLE
ikuai 网页登录端口扫描不到

### ISSUE THREAD

**Issue by Wizzercn** [lcvvvv/kscan#99]

**Comment by lcvvvv** [comment]
方便发下资产吗？

**Comment by Wizzercn** [comment]
@lcvvvv https://114.97.140.23:9493  测完说一声我换IP

**Comment by lcvvvv** [comment]
<img width="1017" alt="图片" src="https://user-images.githubusercontent.com/49975427/186594893-45c02cfc-aecc-4ce0-bd3e-78204a253f9f.png">
端口能发现呀？只是暂时还没包括Ikuai的指纹

**Comment by Wizzercn** [comment]
@lcvvvv 我用的 [v1.76 稳定版](https://github.com/lcvvvv/kscan/releases/tag/v1.76) 使用 ```kscan -t 114.97.140.23``` 扫不出来，另外图片删一下哈，暴露我域名了，，谢谢🙏

**Comment by Wizzercn** [comment]
<img width="607" alt="QQ20220825-150920@2x" src="https://user-images.githubusercontent.com/2408114/186598706-9b7c5180-e86e-4619-9418-1d0c29ad344a.png">

**Comment by lcvvvv** [comment]
#23 

加下我微信吧

**Comment by Wizzercn** [comment]
```kscan -t 114.97.140.23 -p 1-65535```

扫瞄全部端口解决，结贴
